version: "3.8"

services:
  publisher:
    # container_name: service_user
    build:
      context: publisher_service/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - postgesql
      - nats
    networks: [ "nov" ]

  subscriber:
    build:
      context: subscriber_service/
      dockerfile: Dockerfile
    ports:
      - "6080:6080"
    restart: always
    depends_on:
      - postgesql
      - nats
    networks: [ "nov" ]
  postgesql:
    image: postgres:12-alpine
    container_name: nov_postgesql
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=microservice
    volumes:
      - nov:/var/lib/postgresql/data
    networks: [ "nov" ]
  nats:
    image: nats
    ports:
      - "8222:8222"
      - "6222:6222"
      - "4222:4222"
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222 "
    networks: ["nov"]

volumes:
  nov:

networks:
  nov:
    name: nov
